name: Development build

on:
  [push, workflow_dispatch]

jobs:
  build:
    name: Development build
    runs-on: MacStadium
    steps:
      - name: Remove work folders
        env:
          password: ${{ secrets.ELLIE_MINI_SECRET }}
        run: |
          echo $(pwd)
          echo $password | sudo -S rm -rf ./*
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout repository submodules
        run: git submodule update --init --recursive
        
      - name: Build packages
        env:
          password: ${{ secrets.ELLIE_MINI_SECRET }}
        run: |
          export NOSTDIN=1 SUDOPASS=$password
          export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
          gmake -j$(sysctl -n hw.ncpu) dsym

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.ipa
          path: artifacts/net.kdt.pojavlauncher-*.ipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
